"""Initial migration.

Revision ID: 63361eb9a477
Revises: 
Create Date: 2021-01-08 21:41:13.011623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '63361eb9a477'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'schedule_data' not in tables:
        op.create_table('schedule_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('device_id', sa.Integer(), nullable=True),
        sa.Column('start_schedule', sa.Time(), nullable=True),
        sa.Column('end_schedule', sa.Time(), nullable=True),
        sa.Column('last_state', sa.Integer(), nullable=True),
        sa.Column('manual_schedule', sa.Integer(), nullable=True),
        sa.Column('enable_schedule', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if 'sensor_data' not in tables:
        op.create_table('sensor_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('air_temp', sa.Integer(), nullable=True),
        sa.Column('humidity', sa.Numeric(), nullable=True),
        sa.Column('moister', sa.Numeric(), nullable=True),
        sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_data')
    op.drop_table('schedule_data')
    # ### end Alembic commands ###
