"""empty message

Revision ID: 8d31341736ab
Revises: 63361eb9a477
Create Date: 2021-01-08 22:01:30.781069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8d31341736ab'
down_revision = '63361eb9a477'
branch_labels = None
depends_on = None


def upgrade():
    sensor_enum = postgresql.ENUM('SensorTemperature', 'SensorHumidity', name='sensorenum')
    sensor_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_data', sa.Column('sensor', sa.Enum('SensorTemperature', 'SensorHumidity', name='sensorenum'), nullable=True))
    op.add_column('schedule_data', sa.Column('sensor_max', sa.Numeric(), nullable=True))
    op.add_column('schedule_data', sa.Column('sensor_min', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_data', 'sensor_min')
    op.drop_column('schedule_data', 'sensor_max')
    op.drop_column('schedule_data', 'sensor')

    sensor_enum = postgresql.ENUM('SensorTemperature', 'SensorHumidity', name='sensorenum')
    sensor_enum.drop(op.get_bind())
    # ### end Alembic commands ###
